part of 'travel_bloc.dart';

@freezed
class TravelState with _$TravelState {
  const factory TravelState({
    required int index,
    required bool isLoading,
    required List<TravelSpecificProductModel>? travelPopularProductsModel,
    required ProductId? singleProductModel,
    required TravelCitiesModel? travelCitiesModel,
    required ProductId? travelProductsModel,
    required List<ProductId>? searchProducts,
    required List<TravelSpecificProductModel>? travelBestPlacesModel,
    required List<ProductId>? productByLocationModel,
    required int numberOfGuest,
    required String country,
    required List<TravelSearchLocationModels>? travelSearchLocationModels,
    required String searchedLocation,
    required bool showCalendar,
    required int tabIndex,
    required DateTime? selectedStartDate,
    required DateTime? selectedEndDate,
    required DateTime focusDay,
    required String formattedDateRang,
    required List<ProductId>? wishlistProducts,
    required Set<String>? travelWishlistItems,
    required bool bookingSuccess,
    required List<TravelSpecificProductModel>? travelHomeBannerPackages,
    required List<File> formImages,
    required String searchSuccess,
    required TravelProductsByCitiesModel? travelProductsByCitiesModel,
  }) = _TravelState;
  factory TravelState.initial() => TravelState(
        index: 0,
        isLoading: false,
        travelProductsModel: null,
        travelCitiesModel: null,
        searchProducts: null,
        travelPopularProductsModel: null,
        travelBestPlacesModel: null,
        productByLocationModel: null,
        numberOfGuest: 0,
        country: "",
        travelSearchLocationModels: null,
        searchedLocation: "",
        showCalendar: false,
        singleProductModel: null,
        tabIndex: 0,
        selectedEndDate: null,
        selectedStartDate: null,
        focusDay: DateTime.now(),
        formattedDateRang: "",
        wishlistProducts: null,
        travelWishlistItems: {},
        bookingSuccess: false,
        travelHomeBannerPackages: null,
        formImages: [],
        searchSuccess: "",
        travelProductsByCitiesModel: null,
      );
}
