part of 'shop_products_bloc.dart';

@freezed
class ShopProductsState with _$ShopProductsState {
  const factory ShopProductsState({
    required ShopProducts? flashSaleproducts,
    required bool flashSaleLoading,
    required ShopProducts? popularProducts,
    required bool popularProductLoading,
    required RecentProducts? recentProducts,
    required bool recentProductLoading,
    required BannersModel? homeBanner,
    required bool bannersLoading,
    required BannersModel? shopBanner,
    required bool shopBannerLoading,
    required List<Article>? articles,
    required bool articleLoading,
    required bool isLoading,
    required ShopBrandModel? shopBrandModel,
    required WishlistResponse? wishList,
    required String? wishListMessage,
    required Set<String>? wishListItems,
    required ProductModel? searchProducts,
    required ShopBrandProductModel? brandProduct,
    required int index,
    required bool isWishListed,
    required OrderModel? orderModel,
    required OrderModelbyIdModel? ordersByIdModel,
    required int? orderId,
    required String errorMessage,
    required ShopHomeBackgroundCardModel? shopHomeBackgroundCardModelWomens,
    required ShopHomeBackgroundCardHealthyDietModel?
        shopHomeBackgroundCardModelHealthyDiet,
    required SunnahProductHomeCardModel? shopHomeBackgroundCardModelSunnah,
    required ShopAdBrands? shopAdBrands,
    required ShopAdBrandsById? shopAdBrandsById,
    required TopBrandsModel? topBrandsModel,
    required ProductItemsSubCategorySunnahModel?
        productItemsSubCategorySunnahModel,
    required ProductItemsSubCategoryHealthModel?
        productItemsSubCategoryHealthModel,
    required ProductItemsSubCategoryWomenModel?
        productItemsSubCategoryWomenModel,
    required int shopBannerIndex,
    required bool showProgress,
    required int brandBannerIndex,
    required int ordereProgressIndex,
    required int womensCareBannerIndex,
    required int paymentMethod,
    required SpecificCategoryModel? specificCategoryModel,
    required ProductByIdModel? productByIdModel,
    required ProductModel? brandProductsModel,
    required CouponModel? couponModel,
    required bool isPromoCodeAvailable,
    required int indexVal,
    required BrandItemsModel? brandItemsModel,
    required BrandModels? brandModels,
    required ReasonModel? reasonModel,
    required ArticleModelById? articleModelById,
  }) = _Initial;

  factory ShopProductsState.initial() => const ShopProductsState(
        indexVal: -1,
        popularProducts: null,
        flashSaleproducts: null,
        flashSaleLoading: false,
        popularProductLoading: false,
        recentProducts: null,
        recentProductLoading: false,
        homeBanner: null,
        bannersLoading: false,
        shopBanner: null,
        shopBannerLoading: false,
        articles: [],
        articleLoading: false,
        shopBrandModel: null,
        orderId: null,
        errorMessage: "",
        searchProducts: null,
        wishListMessage: "",
        wishListItems: {},
        wishList: null,
        brandProduct: null,
        index: 0,
        ordersByIdModel: null,
        orderModel: null,
        isWishListed: false,
        isLoading: false,
        shopHomeBackgroundCardModelWomens: null,
        shopHomeBackgroundCardModelHealthyDiet: null,
        shopHomeBackgroundCardModelSunnah: null,
        shopAdBrands: null,
        topBrandsModel: null,
        productItemsSubCategoryHealthModel: null,
        productItemsSubCategorySunnahModel: null,
        productItemsSubCategoryWomenModel: null,
        shopBannerIndex: 0,
        brandBannerIndex: 0,
        showProgress: false,
        ordereProgressIndex: -1,
        womensCareBannerIndex: -1,
        shopAdBrandsById: null,
        paymentMethod: 0,
        specificCategoryModel: null,
        productByIdModel: null,
        brandProductsModel: null,
        couponModel: null,
        isPromoCodeAvailable: false,
        brandItemsModel: null,
        brandModels: null,
        reasonModel: null,
        articleModelById: null,
      );
}
