// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAepUudvsRzlbnFiL0pCgsTZtdJj02DK-Y',
    appId: '1:507578207229:web:26b91a036a41117722e794',
    messagingSenderId: '507578207229',
    projectId: 'millat-76f31',
    authDomain: 'millat-76f31.firebaseapp.com',
    storageBucket: 'millat-76f31.appspot.com',
    measurementId: 'G-W0XD6MSZ92',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_E_J8nhq5I9iRJ03YUEYlZBZOw258Sto',
    appId: '1:507578207229:android:e89b00e0c5a8a2f822e794',
    messagingSenderId: '507578207229',
    projectId: 'millat-76f31',
    storageBucket: 'millat-76f31.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfRhWDSdQcAIh6IWlVxw-OWCw_PU5jpR4',
    appId: '1:507578207229:ios:724423a52f9a687222e794',
    messagingSenderId: '507578207229',
    projectId: 'millat-76f31',
    storageBucket: 'millat-76f31.appspot.com',
    iosClientId: '507578207229-jcafor95j4h19trajhehuoithhqi6ub9.apps.googleusercontent.com',
    iosBundleId: 'com.app.millat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfRhWDSdQcAIh6IWlVxw-OWCw_PU5jpR4',
    appId: '1:507578207229:ios:724423a52f9a687222e794',
    messagingSenderId: '507578207229',
    projectId: 'millat-76f31',
    storageBucket: 'millat-76f31.appspot.com',
    iosClientId: '507578207229-jcafor95j4h19trajhehuoithhqi6ub9.apps.googleusercontent.com',
    iosBundleId: 'com.app.millat',
  );
}
