part of 'quran_bloc.dart';

@freezed
class QuranState with _$QuranState {
  const factory QuranState(
      {required bool isLoading,
      required QuranChapters? quranChaptersModel,
      required ChapterVersesModel? chapterVersesModel,
      required ParaVersesModel? paraVersesModel,
      required QuranParaModel? quranParaModel,
      required List<ChapterByIdModel>? chapterByIdModel,
      required List<Chapters>? searchChapters,
      required bool isExpand2,
      required List<VersesByKeyModel>? versesByKeyModel,
      required bool audioPlaying,
      required bool audioPaused,
      required bool audioStopped,
      required List<dynamic> paraAudios,
      required List<dynamic> chapterAudios,
      // required TranslationsModel? translationsModel,
      required int currentSettingBgIndex,
      required double fontsize,
      required List<String?>? chapterTranslationText,
      required List<String?>? paraTranslationText,
      required bool isShowMusicbar,
      required int audioIndex,
      required bool isExpand,
      required int globalTransilationId,
      required String transilationName,
      required RecitationModel? recitationsModel,
      required String recitorName,
      required int recitorId,
      required String quranTextTypeName,
      required ParaVersesModelOfUthmani? paraVersesModelofUthmani,
      required ParaVersesModelOfNoSymbol? paraVersesModelofNoSymbol,
      required String chapterName,
      required int nxtAndprevValue}) = _QuranState;
  factory QuranState.initial() => const QuranState(
      isLoading: false,
      quranChaptersModel: null,
      chapterVersesModel: null,
      paraVersesModel: null,
      quranParaModel: null,
      chapterByIdModel: null,
      searchChapters: [],
      versesByKeyModel: [],
      isExpand2: false,
      audioPlaying: false,
      audioPaused: false,
      audioStopped: false,
      paraAudios: [],
      chapterAudios: [],
      currentSettingBgIndex: -1,
      fontsize: 17.0,
      // translationsModel: null,
      chapterTranslationText: [],
      paraTranslationText: [],
      audioIndex: -1,
      isShowMusicbar: false,
      isExpand: false,
      recitationsModel: null,
      chapterName: "",
      quranTextTypeName: 'indopak',
      recitorId: 7,
      recitorName: 'Mishari Rashid al-`Afasy',
      globalTransilationId: 131,
      paraVersesModelofUthmani: null,
      paraVersesModelofNoSymbol: null,
      nxtAndprevValue: 1,
      transilationName: "English (Dr. Mustafa Khattab, the Clear Quran)");
}
