part of 'quran_bloc.dart';

@freezed
class QuranState with _$QuranState {
  const factory QuranState({
    required bool isLoading,
    required List<QuranSurahModel>? quranSurahModel,
    required ChapterVersesModel? chapterVersesModel,
    required ParaVersesModel? paraVersesModel,
    required List<QuranParaModel>? quranParaModel,
    required List<ChapterByIdModel>? chapterByIdModel,
    required List<QuranSurahModel>? searchChapters,
    required bool isExpand2,
    required List<VersesByKeyModel>? versesByKeyModel,
    required bool audioPlaying,
    required bool audioPaused,
    required bool audioStopped,
    required List<dynamic> paraAudios,
    required List<dynamic> chapterAudios,
    required TranslationsModel? translationsModel,
    required int currentSettingBgIndex,
    required double fontsize,
    required List<String?>? chapterTranslationText,
    required List<String?>? paraTranslationText,
    required bool isShowMusicbar,
    required int audioIndex,
    required bool isExpand,
    required int globalTransilationId,
    required String transilationName,
    required RecitationsModel? recitationsModel,
    required String recitorName,
    required int recitorId,
    required String quranTextTypeName,
    required ChapterVersesIndoPakModel? chapterVersesIndoPakModel,
    required ChapterVersesOfUthmani? chapterVersesOfUthmani,
    required ChapterVersesOfNosymbol? chapterVersesOfNosymbol,
    required ParaVersesModelofUthmani? paraVersesModelofUthmani,
    required ParaVersesModelofNoSymbol? paraVersesModelofNoSymbol,
    required String chapterName,
    required int nxtAndprevValue,
    required List<String> tempListAya,
    required String lastRead,
    required String singleTranslation,
    required List<String> bookmarkAudioPlaylist,
    required String shuffleVersKey,
  }) = _QuranState;
  factory QuranState.initial() => const QuranState(
        isLoading: false,
        quranSurahModel: null,
        chapterVersesModel: null,
        paraVersesModel: null,
        quranParaModel: null,
        chapterByIdModel: null,
        searchChapters: [],
        versesByKeyModel: [],
        isExpand2: false,
        audioPlaying: false,
        audioPaused: false,
        audioStopped: false,
        paraAudios: [],
        chapterAudios: [],
        currentSettingBgIndex: -1,
        fontsize: 18.0,
        translationsModel: null,
        chapterTranslationText: [],
        paraTranslationText: [],
        audioIndex: -1,
        isShowMusicbar: true,
        isExpand: false,
        recitationsModel: null,
        chapterName: "",
        quranTextTypeName: 'indopak',
        recitorId: 7,
        recitorName: 'Mishari Rashid al-`Afasy',
        globalTransilationId: 131,
        paraVersesModelofUthmani: null,
        paraVersesModelofNoSymbol: null,
        chapterVersesIndoPakModel: null,
        chapterVersesOfNosymbol: null,
        chapterVersesOfUthmani: null,
        nxtAndprevValue: 1,
        tempListAya: ["1:2", "2:2", "3:4", "4:5"],
        transilationName: "English (Dr. Mustafa Khattab, the Clear Quran)",
        lastRead: "1:1",
        singleTranslation: "",
        bookmarkAudioPlaylist: [],
        shuffleVersKey: "2:2",
      );
}
