part of 'namaz_timing_bloc.dart';

@freezed
class NamazTimingState with _$NamazTimingState {
  const factory NamazTimingState({
    required String success,
    required String error,
    required PrayerModel? prayerModel,
    required Map<String, dynamic>? currentNamaz,
    required Map<String, dynamic>? upcomingNamaz,
    required bool showImsak,
    required String urlDate,
    required int school,
    required bool isArtCalcMehod,
    required int method,
    required String namazMethodName,
    required String methodPlace,
    required List<NamazTimeData>? namazMethodsModel,
    required int highLatMethodVal,
    required String arabicDate,
    required int index,
    required bool notifyFajr,
    required bool notifyDhuhr,
    required bool notifyAsr,
    required bool notifyMagrib,
    required bool notifyIsha,
    required bool notifySunrise,
    required bool notifyQiyam,
    required bool autoDetectLocationDb,
    required bool automaticSettingsDb,
    required bool showImsakDb,
    required String location,
    required int calculationMethod,
    required int asrCalculationMehod,
    required int manualCorrections,
  }) = _Initial;
  factory NamazTimingState.initial() => NamazTimingState(
        success: "",
        error: "",
        index: -1,
        prayerModel: null,
        currentNamaz: {},
        upcomingNamaz: {},
        showImsak: false,
        school: 0,
        isArtCalcMehod: true,
        method: 1,
        methodPlace: "",
        namazMethodName: "",
        highLatMethodVal: 0,
        namazMethodsModel: [],
        arabicDate: "",
        notifyAsr: true,
        notifyDhuhr: true,
        notifyFajr: true,
        notifyIsha: true,
        notifyMagrib: true,
        notifyQiyam: true,
        notifySunrise: true,
        urlDate: DateFormat('dd-MM-yyyy').format(DateTime.now()).toString(),
        autoDetectLocationDb: true,
        automaticSettingsDb: true,
        showImsakDb: false,
        location: "",
        calculationMethod: 0,
        asrCalculationMehod: 0,
        manualCorrections: 0,
      );
}
